### ISSUE TITLE
What are `nil` and `NIL`?

### ISSUE THREAD

**Issue by reynoldsnlp** [matgrioni/UD#1]
I tried running `consistency.py` on [the Chinese UD corpus](https://raw.githubusercontent.com/UniversalDependencies/UD_Chinese-GSD/master/zh_gsd-ud-train.conllu) and the output contains many `nil` and `NIL` labels. `nil` is always left of the `|` and `NIL`s are always to the right of the `|`.

I think I have figured out that `NIL` means that there is no direct dependency between the tokens. I cannot figure out what `nil` means, and there is no mention of it in the paper.

**Comment by matgrioni** [comment]
Hi reynoldsnlp,

Thanks for the bringing this issue up. Could you please provide your output and the exact command line arguments you provided if you have it on hand so I can understand exactly what you are seeing.

As you correctly determined, a `NIL` relationship means that there is no relationship between the lemmas in one occurrence, but there is a relationship elsewhere in the corpus, and these occurrences have the same contexts, so the script flags them as possibly inconsistent. I am not familiar / do not remember `nil` being used for something specific as opposed to `NIL`. I will ping back if I can reproduce this result.

**Comment by matgrioni** [comment]
Ah after running, I see what you are referring to now. So the item to the left of the bar is the type of inconsistency the script is flagging. There are two types of inconsistencies, those that are based on context, and those based on lack of annotation. `context` inconsistencies are when two lemma pair occurrences with the context are annotated differently. `null` inconsistencies are when two lemma pair occurrences are not related directly (are not head and child), but have the same context.

The naming is a bit confusing and not well defined in the README, but hopefully this clears up the output. If you have any more questions about the script, feel free to make another issue!

**Comment by reynoldsnlp** [comment]
Thanks! That is what we suspected, but it's good to have it confirmed. :)
